# This workflow will run the Camunda Engine Test Suite with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Engine Test Suite

on:
  push:
    branches:
      - engine-test-suite-with-child-processes
      - engine-test-suite-without-child-processes
  pull_request:
    branches:
      - engine-test-suite-with-child-processes
      - engine-test-suite-without-child-processes

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-engine-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-engine-maven-
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        # Artifact name
        name: Package
        # Destination path
        path: staging
    - name: Install On-demand Call Activity Plugin
      run: mvn --batch-mode install:install-file -Dfile=staging/engine-plugin-on-demand-call-activity-*.jar
    - name: Test with Maven
      run: mvn --projects engine --batch-mode test --file pom.xml
